version: "3.9"
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: prod # Aquí indicamos el entorno de producción
    ports:
      - "8001:8080"
    depends_on:
      - db
    networks:
      - spring

  db:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: 45549813O
      MYSQL_DATABASE: "futbolistas_db"
    ports:
      - "3306:3306"
    networks:
      - spring

networks:
  spring:
    driver: bridge
