services:
  app:
    build:
      context: .
    image: futbolistas
    container_name: servicio-futbolistas
    restart: "no"  # No se reinicia en desarrollo
    environment:
      - SPRING_APP_PORT=${SPRING_APP_PORT}
    ports:
      - ${SPRING_APP_PORT}:8080
    networks:
      - spring
networks:
  spring:
    external: true
